// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dune/dtp/v1/message.proto

package dtpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message is one application message, preceded by a 4-byte big-endian size.
// This MVP wire format is dune-mvp/2, not the historical DTP/1 Frame.
// kind: hello, welcome, request, accepted, result, error, data, input,
// written, resize, signal, eof, exit, stderr, lease_request, lease_grant,
// lease_ready. payload is UTF-8 JSON with
// operation-specific schemas defined by pkg/api; data is uninterpreted bytes.
// Stream IDs and transport acknowledgements belong exclusively to Yamux.
type Message struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Kind                 string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RequestId            string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Operation            string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Target               string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Incarnation          string                 `protobuf:"bytes,5,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	ConnectionGeneration uint64                 `protobuf:"varint,6,opt,name=connection_generation,json=connectionGeneration,proto3" json:"connection_generation,omitempty"`
	RuntimeId            string                 `protobuf:"bytes,7,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	RuntimeGeneration    uint64                 `protobuf:"varint,8,opt,name=runtime_generation,json=runtimeGeneration,proto3" json:"runtime_generation,omitempty"`
	Payload              []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Data                 []byte                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string                 `protobuf:"bytes,11,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string                 `protobuf:"bytes,12,opt,name=detail,proto3" json:"detail,omitempty"`
	RuntimeIncarnation   string                 `protobuf:"bytes,13,opt,name=runtime_incarnation,json=runtimeIncarnation,proto3" json:"runtime_incarnation,omitempty"`
	// Mandatory on Gateway-to-fabricd business messages and lease control frames.
	InputLeaseId string `protobuf:"bytes,14,opt,name=input_lease_id,json=inputLeaseId,proto3" json:"input_lease_id,omitempty"`
	// Relative grant duration on welcome/lease_grant only, bounded by the protocol.
	InputLeaseMs uint32 `protobuf:"varint,15,opt,name=input_lease_ms,json=inputLeaseMs,proto3" json:"input_lease_ms,omitempty"`
	// Ownership identity for directory-backed routes; both absent in local mode.
	RouteRecovery string `protobuf:"bytes,16,opt,name=route_recovery,json=routeRecovery,proto3" json:"route_recovery,omitempty"`
	RouteEpoch    uint64 `protobuf:"varint,17,opt,name=route_epoch,json=routeEpoch,proto3" json:"route_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_dune_dtp_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_dune_dtp_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_dune_dtp_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Message) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Message) GetIncarnation() string {
	if x != nil {
		return x.Incarnation
	}
	return ""
}

func (x *Message) GetConnectionGeneration() uint64 {
	if x != nil {
		return x.ConnectionGeneration
	}
	return 0
}

func (x *Message) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *Message) GetRuntimeGeneration() uint64 {
	if x != nil {
		return x.RuntimeGeneration
	}
	return 0
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Message) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Message) GetRuntimeIncarnation() string {
	if x != nil {
		return x.RuntimeIncarnation
	}
	return ""
}

func (x *Message) GetInputLeaseId() string {
	if x != nil {
		return x.InputLeaseId
	}
	return ""
}

func (x *Message) GetInputLeaseMs() uint32 {
	if x != nil {
		return x.InputLeaseMs
	}
	return 0
}

func (x *Message) GetRouteRecovery() string {
	if x != nil {
		return x.RouteRecovery
	}
	return ""
}

func (x *Message) GetRouteEpoch() uint64 {
	if x != nil {
		return x.RouteEpoch
	}
	return 0
}

var File_dune_dtp_v1_message_proto protoreflect.FileDescriptor

const file_dune_dtp_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x19dune/dtp/v1/message.proto\x12\vdune.dtp.v1\"\xb6\x04\n" +
	"\aMessage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12 \n" +
	"\vincarnation\x18\x05 \x01(\tR\vincarnation\x123\n" +
	"\x15connection_generation\x18\x06 \x01(\x04R\x14connectionGeneration\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\a \x01(\tR\truntimeId\x12-\n" +
	"\x12runtime_generation\x18\b \x01(\x04R\x11runtimeGeneration\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x12\x12\n" +
	"\x04code\x18\v \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\f \x01(\tR\x06detail\x12/\n" +
	"\x13runtime_incarnation\x18\r \x01(\tR\x12runtimeIncarnation\x12$\n" +
	"\x0einput_lease_id\x18\x0e \x01(\tR\finputLeaseId\x12$\n" +
	"\x0einput_lease_ms\x18\x0f \x01(\rR\finputLeaseMs\x12%\n" +
	"\x0eroute_recovery\x18\x10 \x01(\tR\rrouteRecovery\x12\x1f\n" +
	"\vroute_epoch\x18\x11 \x01(\x04R\n" +
	"routeEpochB0Z.github.com/aiomni/dune/proto/dune/dtp/v1;dtpv1b\x06proto3"

var (
	file_dune_dtp_v1_message_proto_rawDescOnce sync.Once
	file_dune_dtp_v1_message_proto_rawDescData []byte
)

func file_dune_dtp_v1_message_proto_rawDescGZIP() []byte {
	file_dune_dtp_v1_message_proto_rawDescOnce.Do(func() {
		file_dune_dtp_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dune_dtp_v1_message_proto_rawDesc), len(file_dune_dtp_v1_message_proto_rawDesc)))
	})
	return file_dune_dtp_v1_message_proto_rawDescData
}

var file_dune_dtp_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dune_dtp_v1_message_proto_goTypes = []any{
	(*Message)(nil), // 0: dune.dtp.v1.Message
}
var file_dune_dtp_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dune_dtp_v1_message_proto_init() }
func file_dune_dtp_v1_message_proto_init() {
	if File_dune_dtp_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dune_dtp_v1_message_proto_rawDesc), len(file_dune_dtp_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dune_dtp_v1_message_proto_goTypes,
		DependencyIndexes: file_dune_dtp_v1_message_proto_depIdxs,
		MessageInfos:      file_dune_dtp_v1_message_proto_msgTypes,
	}.Build()
	File_dune_dtp_v1_message_proto = out.File
	file_dune_dtp_v1_message_proto_goTypes = nil
	file_dune_dtp_v1_message_proto_depIdxs = nil
}
